export const CREATE_QUEST_LOADING = "CREATE_QUEST_LOADING";

export const CREATE_QUEST_SUCCESS = "CREATE_QUEST_SUCCESS";

export const CREATE_QUEST_ERROR = "CREATE_QUEST_ERROR";


export const DELETE_QUEST_LOADING = "DELETE_QUEST_LOADING";

export const DELETE_QUEST_SUCCESS = "DELETE_QUEST_SUCCESS";

export const DELETE_QUEST_ERROR = "DELETE_QUEST_ERROR";


export const INIT_QUEST_LOADING = "INIT_QUEST_LOADING";

export const INIT_QUEST_SUCCESS = "INIT_QUEST_SUCCESS";

export const INIT_QUEST_ERROR = "INIT_QUEST_ERROR";